[sys]
http-addr = "0.0.0.0"
http-port = "5666"
print-routes = true

[log]
level = "INFO"
log-store-path = "logs/"
latest-filename = "gx-customs-bridge.log"
log-in-console = true
log-in-rotate-file = true

[access-token]
access-token-minute-duration = 1
access-token-secret = "qpwoalskzmxn1029"
enabled = true

[refresh-token]
refresh-token-minute-duration = 24
refresh-token-secret = "122f9dfjkdsla"

[db]
db-type = "mssql"
username = ""
password = ""
addr = ""
port = ""
schema = ""
configs = ""
max-idle-conns = 10
max-open-conns = 50
conn-max-lifetime = 14400
enable-log = false

[customs]
imp-path = ''
sys-id = ''
dcl-er-conc = ''
ic-card-no = ''
oper-cus-reg-code = ''

[rabbitmq]
addr = ""
queue-name = ""

[i18n]
bundle-dir = ""
